# Netlify configuration for Portal Finder frontend
[build]
  # Build command (if needed)
  command = "echo 'No build required for static frontend'"
  
  # Directory to deploy (frontend folder only)
  publish = "frontend"

# Redirect all API calls to the backend server
[[redirects]]
  from = "/api/*"
  to = "https://portal-finder.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback for any unmatched routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Headers for API responses
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"